### ISSUE TITLE
The language for the grammar does not match the language of the speech recognizer.

### ISSUE THREAD

**Issue by dragonmcmx1** [LoafOrc/VoiceRecognitionAPI#4]
Trying to get this mod to work, but encountering the following error when loading:

```
[Error  : Unity Log] InvalidOperationException: The language for the grammar does not match the language of the speech recognizer.
Stack trace:
System.Speech.Recognition.RecognizerBase.ThrowIfSapiErrorCode (System.Speech.Internal.SapiInterop.SAPIErrorCodes errorCode) (at <eabef287471f4e019f1d853d46365e9c>:0)
System.Speech.Recognition.RecognizerBase.LoadSapiGrammarFromCfg (System.Speech.Internal.SapiInterop.SapiGrammar sapiGrammar, System.Speech.Recognition.Grammar grammar, System.Uri baseUri, System.Boolean enabled, System.Single weight, System.Int32 priority) (at <eabef287471f4e019f1d853d46365e9c>:0)
System.Speech.Recognition.RecognizerBase.LoadSapiGrammar (System.Speech.Recognition.Grammar grammar, System.Speech.Internal.SapiInterop.SapiGrammar sapiGrammar, System.Boolean enabled, System.Single weight, System.Int32 priority) (at <eabef287471f4e019f1d853d46365e9c>:0)
System.Speech.Recognition.RecognizerBase.LoadGrammar (System.Speech.Recognition.Grammar grammar) (at <eabef287471f4e019f1d853d46365e9c>:0)
System.Speech.Recognition.SpeechRecognitionEngine.LoadGrammar (System.Speech.Recognition.Grammar grammar) (at <eabef287471f4e019f1d853d46365e9c>:0)
VoiceRecognitionAPI.SpeechHandler..ctor () (at <b36d1ff393ed4c77b8b78515ea74824f>:0)
VoiceRecognitionAPI.Plugin.SetupEngine () (at <b36d1ff393ed4c77b8b78515ea74824f>:0)
VoiceRecognitionAPI.Patches.GameNetworkManagerPatch.setupRecognitionEngine () (at <b36d1ff393ed4c77b8b78515ea74824f>:0)
(wrapper dynamic-method) GameNetworkManager.DMD<GameNetworkManager::Start>(GameNetworkManager)
```

Playing on Windows 10, latest version (v45) of LC, the API (1.0.2) and ShipVoiceCommands (1.4.0). My PC language is set to English (US). Voice recognition is enabled and set to Microsoft Speech Recognizer 8.0 for Windows (English - US).

Is there anything I can do on my end to fix this, or could you update the mod if not?

**Comment by LoafOrc** [comment]
This error seems more like a mod is registering a voice phrase that is not English. Please provide the lines before the error so that I can see what phrases are being registered.

**Comment by dragonmcmx1** [comment]
[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (30.11.2023 00:00:47)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [VoiceRecognitionAPI 1.0.2]
[Info   :me.loaforc.voicerecognitionapi] Patching game...
[Info   :me.loaforc.voicerecognitionapi] VoiceRecognitionAPI:1.0.2 has succesfully loaded!
[Info   :   BepInEx] Loading [ShipVoiceCommands 1.4.0]
[Info   :me.loaforc.shipvoicecommands] Setting up config.
[Info   :me.loaforc.shipvoicecommands] Registering voice commands!
[Info   :me.loaforc.voicerecognitionapi] System.String[]
[Info   :me.loaforc.voicerecognitionapi] System.String[]
[Info   :me.loaforc.voicerecognitionapi] System.String[]
[Info   :me.loaforc.voicerecognitionapi] System.String[]
[Info   :me.loaforc.voicerecognitionapi] System.String[]
[Info   :me.loaforc.voicerecognitionapi] System.String[]
[Info   :me.loaforc.shipvoicecommands] ShipVoiceCommands:1.4.0 has succesfully loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: -0,05
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: -0,05; (0.00, 0.00, 0.00, -0.05) (True)
[Info   : Unity Log] Saving changed settings
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: -0,05
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: -0,05; (0.00, 0.00, 0.00, -0.05) (True)
[Info   : Unity Log] subcribing to steam callbacks
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: -0,05
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: -0,05; (0.00, 0.00, 0.00, -0.05) (True)
[Info   :me.loaforc.voicerecognitionapi] Setting up the recognition engine.
[Info   :me.loaforc.voicerecognitionapi] Importing System.Speech
[Info   :me.loaforc.voicerecognitionapi] Located at: VoiceRecognitionAPI.System.Speech.dll
[Info   :me.loaforc.voicerecognitionapi] Found file! Length: 692224
[Info   :me.loaforc.voicerecognitionapi] Loaded System.Speech, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[Info   :me.loaforc.voicerecognitionapi] open doors
[Info   :me.loaforc.voicerecognitionapi] open ship doors
[Info   :me.loaforc.voicerecognitionapi] close doors
[Info   :me.loaforc.voicerecognitionapi] close ship doors
[Info   :me.loaforc.voicerecognitionapi] teleport
[Info   :me.loaforc.voicerecognitionapi] teleport player
[Info   :me.loaforc.voicerecognitionapi] camera switch
[Info   :me.loaforc.voicerecognitionapi] switch camera
[Info   :me.loaforc.voicerecognitionapi] camera next
[Info   :me.loaforc.voicerecognitionapi] camera on
[Info   :me.loaforc.voicerecognitionapi] camera off
[Info   :me.loaforc.voicerecognitionapi]  camera toggle
[Info   :me.loaforc.voicerecognitionapi] lights on
[Info   :me.loaforc.voicerecognitionapi] lights off
[Info   :me.loaforc.voicerecognitionapi] toggle lights
[Info   :me.loaforc.voicerecognitionapi] night night
[Info   :me.loaforc.voicerecognitionapi] Phrases used for voice recognition: System.Collections.Generic.List`1[System.String]
[Info   :me.loaforc.voicerecognitionapi] Importing System.Speech.resources
[Info   :me.loaforc.voicerecognitionapi] Located at: VoiceRecognitionAPI.System.Speech.resources.dll
[Info   :me.loaforc.voicerecognitionapi] Importing System.Speech.resources, Version=3.0.0.0, Culture=de-DE, PublicKeyToken=31bf3856ad364e35
[Info   :me.loaforc.voicerecognitionapi] Located at: VoiceRecognitionAPI.System.Speech.resources.dll
[Info   :me.loaforc.voicerecognitionapi] Importing System.Speech.resources
[Info   :me.loaforc.voicerecognitionapi] Located at: VoiceRecognitionAPI.System.Speech.resources.dll
[Info   :me.loaforc.voicerecognitionapi] Importing System.Speech.resources, Version=3.0.0.0, Culture=de, PublicKeyToken=31bf3856ad364e35
[Info   :me.loaforc.voicerecognitionapi] Located at: VoiceRecognitionAPI.System.Speech.resources.dll
[Error  : Unity Log] InvalidOperationException: The language for the grammar does not match the language of the speech recognizer.

This is on a fresh profile with no other mods.

**Comment by LoafOrc** [comment]
Hi! Thanks for getting back, could you please try the following [debug version](https://cdn.discordapp.com/attachments/602207979105681451/1190454162710872114/VoiceRecognitionAPI.dll?ex=65a1dbd5&is=658f66d5&hm=8dacd5f82196a45f534ee904535b3c8daccf4b4a829e29708d76d492d9de7075&) that contains a hotfix, and tell me if this solves the issue?

**Comment by dragonmcmx1** [comment]
I replaced the dll in the plugins folder with the new one. Didn't seem to work, starting the game gave me the following:

[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (30.11.2023 00:00:47)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [VoiceRecognitionAPI 1.0.2]
[Warning: Unity Log] The script 'VoiceRecognitionAPI.Plugin' could not be instantiated!
[Info   :   BepInEx] Loading [ShipVoiceCommands 1.4.0]
[Info   :me.loaforc.shipvoicecommands] Setting up config.
[Info   :me.loaforc.shipvoicecommands] Registering voice commands!
[Error  : Unity Log] TypeLoadException: Could not load type of field 'VoiceRecognitionAPI.Plugin:successMessage' (9) due to: Could not load file or assembly 'LethalSettings, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
ShipVoiceCommands.ShipVoiceCommandsBase.Awake () (at <f5551979c02f488f8ddef905b852b10c>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[Message:   BepInEx] Chainloader startup complete

**Comment by LoafOrc** [comment]
Oh yeah sorry! I've been working on importing [an ingame way to test voice recognition](https://thunderstore.io/c/lethal-company/p/willis81808/LethalSettings/) so you'll need to download that dll.

**Comment by dragonmcmx1** [comment]
With that it worked. Thank you so much for the quick troubleshooting!

**Comment by LoafOrc** [comment]
Will be fixed with the next update to thunderstore!
